import '../page.css';
import masterthesis from "../../images/masterthesis.png";

let MasterThesis = () => {
    return (
        <div>
            <h2>Master Thesis</h2>
            <p><strong>Title:</strong> Learning to track a model-based controller from randomized footholds. <br /><strong>Lab:</strong> Robotic Systems Lab, ETH.</p>
            <img src={masterthesis} alt="masterthesis" class="image-resized"></img>
            <h3>Abstract</h3>
            <p> This work focuses on the challenge of quadrupedal locomotion in terrains that require precise foothold planning and foot placement. We demonstrate that a control
                policy capable of tracking desired footholds to navigate stairs, slopes, obstacles,
                and stepping stones can be effectively learned in simulation using Deep Reinforcement Learning (DRL) and successfully deployed on a real robot to track footholds
                generated by a model-based controller. During training, the reference footholds are
                computed based on the policy’s value function and a simple kinematic model, which
                replaces the model-based controller and significantly reduces the training time. </p>
        </div>
    );
};

export default MasterThesis;
